name: CI/CD for website

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - run: mise run generate-docs
      - run: mise run generate-web
      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-artifacts
          path: website/typst-docs-web/dist
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: website/typst-docs-web/dist # The folder the action should deploy.

  textlint-md:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup tools
        uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint Markdown using textlint
        run: bun run --bun textlint-md

  textlint-html:
    runs-on: ubuntu-24.04
    needs: build-and-deploy
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download build artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: build-artifacts
          path: website/typst-docs-web/dist
      - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint HTML using textlint
        run: bun run --bun textlint-html

  website-ci:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: website/typst-docs-web
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: biome
            name: "Run Biome CI"
            command: "bun biome ci ."
          - task: vitest
            name: "Run test runner"
            command: "bun run test"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup tools
        uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}
